var express = require('express');
var router = express.Router();
const router_name = require('../app/Controllers/AllRouteNameController');
const validate=require('../request/PostionRequest');
router.get('/listAllRouterName',router_name.index);
router.post('/storeAllRouterName',router_name.create);
router.get('/editAllRouterName/:id',router_name.edit);
router.put('/updateAllRouterName/:id',router_name.update);
router.delete('/deleteAllRouterName/:id',router_name.destroy);
module.exports = router;