var express = require('express');
var router = express.Router();
const Assemble = require('../app/Controllers/AssembleController');
//const validate=require('../request/CategoriesSimRequest');
router.get('/listAssemble',Assemble.AssembleList);
router.get('/showDetailAssemble/:id',Assemble.showDetailAssemble);
router.put('/approveOrderAssemble/:id',Assemble.approveAssembleOrder);
router.get('/infotoUpdateAssemble/:id',Assemble.infotoUpdate);
router.put('/updateOrderAssemble/:id',Assemble.updateAssembleOrder);
// router.put('/checkWelding/:id',Welding.checkWelding);
module.exports = router;
