var express = require('express');
var router = express.Router();
const Dashboard = require('../app/Controllers/DashboardController');
const Auth =require('../app/middlewares/authenticatetion');
const Permision =require('../app/middlewares/authorization');
//const validate=require('../request/DepartmentRequest');
router.get('/header-report',Auth.checkAuth,Permision.checkPermision,Dashboard.HeaderReport);
// router.get('/bar-chart-report',Auth.checkAuth,Permision.checkPermision,Dashboard.BarChartReport);
// router.get('/pie-chart-report',Auth.checkAuth,Permision.checkPermision,Dashboard.PieChartReport);
router.get('/totalProductOrderByYear',Dashboard.totalProductOrderByYear);
router.get('/totalJobsheetByYear',Dashboard.totalJobsheetByYear);
router.get('/totalProductByYear',Dashboard.totalProductByYear);
router.get('/totalSemiProductByYear',Dashboard.totalSemiProductByYear);
router.get('/listJobsheetByYear',Dashboard.listJobsheetByYear);
router.get('/listDetailMonthJobsheetbyYear/:id',Dashboard.listDetailMonthJobsheetbyYear);
router.get('/listProductOrderByYear',Dashboard.listProductOrderByYear);
router.get('/listDetailMonthProductOrderbyYear/:id',Dashboard.listDetailMonthProductOrderbyYear);
router.get('/listSemiProductByYear',Dashboard.listSemiProductByYear);
router.get('/listDetailMonthSemiProductbyYear/:id',Dashboard.listDetailMonthSemiProductbyYear);
router.get('/listProductByYear',Dashboard.listProductByYear);
router.get('/listDetailMonthProductbyYear/:id',Dashboard.listDetailMonthProductbyYear);
router.get('/listDetailProductOrderbyYear',Dashboard.listDetailProductOrderbyYear);
router.get('/listDetailJobsheetbyYear',Dashboard.listDetailJobsheetbyYear);
router.get('/listDetailSemiProductbyYear',Dashboard.listDetailSemiProductbyYear);
router.get('/listDetailProductbyYear',Dashboard.listDetailProductbyYear);
router.get('/listDetailMonthProductOrderTypeByYear/:id',Dashboard.listDetailMonthProductOrderTypeByYear);
router.get('/listDetailMonthJobsheetTypeByYear/:id',Dashboard.listDetailMonthJobsheetTypeByYear);
router.get('/listDetailMonthSemiProductTypeByYear/:id',Dashboard.listDetailMonthSemiProductTypeByYear);
router.get('/listDetailMonthProductTypeByYear/:id',Dashboard.listDetailMonthProductTypeByYear);
router.get('/listYear',Dashboard.ListYear);
module.exports = router;
