var express = require('express');
var router = express.Router();
const Dashboard = require('../app/Controllers/DashboardController');
const Auth =require('../app/middlewares/authenticatetion');
const Permision =require('../app/middlewares/authorization');
//const validate=require('../request/DepartmentRequest');
router.get('/header-report',Auth.checkAuth,Permision.checkPermision,Dashboard.HeaderReport);
router.get('/bar-chart-report',Auth.checkAuth,Permision.checkPermision,Dashboard.BarChartReport);
router.get('/pie-chart-report',Auth.checkAuth,Permision.checkPermision,Dashboard.PieChartReport);
module.exports = router;
