var express = require('express');
var router = express.Router();
const detailproductorder = require('../app/Controllers/DetailProductOrderController');
const validate=require('../request/DetailProductOrderRequest');
const Auth =require('../app/middlewares/authenticatetion');
const Permision =require('../app/middlewares/authorization');
router.get('/DetailProductOrder',Auth.checkAuth,Permision.checkPermision,detailproductorder.index);
router.post('/storeDetailProductOrder',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,detailproductorder.store);
router.put('/updateDetailProductOrder/:id',Auth.checkAuth,Permision.checkPermision,detailproductorder.update);
 router.delete('/deleteDetailProductOrder',Auth.checkAuth,Permision.checkPermision,detailproductorder.destroy);
module.exports = router;
