var express = require('express');
var router = express.Router();
const donvitinh = require('../app/Controllers/DonvitinhController');
const validate=require('../../request/validate_donvitinh');
router.get('/',donvitinh.index);
router.post('/store',validate.validate_donvitinh(),donvitinh.store);
router.get('/edit/:id',donvitinh.edit);
router.put('/update/:id',validate.validate_donvitinh(),donvitinh.update);
router.delete('/delete/:id',donvitinh.destroy);
router.post('/search',donvitinh.search);
module.exports = router;