var express = require('express');
var router = express.Router();
const invoice_nhap = require('../app/Controllers/InvoiceNhapController');
const validate=require('../../request/validate_invoice_nhap');
router.get('/',invoice_nhap.index);
router.post('/store',validate.validate_invoice_nhap(),invoice_nhap.store);
router.get('/edit/:id',invoice_nhap.edit);
router.put('/update/:id',validate.validate_invoice_nhap(),invoice_nhap.update);
router.delete('/delete/:id',invoice_nhap.destroy);
router.post('/search',invoice_nhap.search);
module.exports = router;