var express = require('express');
var router = express.Router();
const jobsheet = require('../app/Controllers/JobsheetController');
const validate=require('../request/PostionRequest');
router.get('/',jobsheet.index);
router.get('/create',jobsheet.infotoCreate);
router.post('/store',jobsheet.store);
router.get('/edit/:id',jobsheet.edit);
router.put('/update/:id',jobsheet.update);
// router.delete('/delete',position.destroy);
module.exports = router;
