var express = require('express');
var router = express.Router();
const jobsheet = require('../app/Controllers/JobsheetController');
const validate=require('../request/PostionRequest');
router.get('/listJobsheet',jobsheet.index);
router.get('/create',jobsheet.infotoCreate);
router.post('/storeJobSheet',jobsheet.store);
router.get('/editJobSheet/:id',jobsheet.edit);
router.put('/updateJobSheet/:id',jobsheet.update);
router.put('/cancelJobSheet/:id',jobsheet.cancel);
router.get('/showDetailJobSheet/:id',jobsheet.showDetail);
router.put('/OrderExportMaterialsJobSheet',jobsheet.OrderExportMaterials);
router.put('/ExportMaterialsJobSheet',jobsheet.ExportMaterials);
router.put('/OrderProductJobSheet',jobsheet.OrderProduct);
router.put('/OrderQCJobSheet',jobsheet.OrderQC);
router.put('/OrderStoreJobSheet',jobsheet.OrderStore);
router.put('/StoreWarehouseJobSheet',jobsheet.Store);
router.get('/infoCreatOrderQCJobSheet',jobsheet.infoCreatOrderQC);   //no use
// router.put('/OrderProductQC/:id',jobsheet.OrderProductQC);
// router.put('/OrderSemiProductQC/:id',jobsheet.OrderSemiProductQC);
// router.put('/OrderStoreSemiProduct/:id',jobsheet.OrderStoreSemiProduct);
// router.put('/OrderStoreProduct/:id',jobsheet.OrderStoreProduct);
// router.put('/StoreProduct/:id',jobsheet.StoreProduct);
// router.put('/StoreSemiProduct/:id',jobsheet.StoreSemiProduct);
module.exports = router;
