var express = require('express');
var router = express.Router();
const lydoxuat = require('../app/Controllers/LydoXuatController');
const validate=require('../../request/validate_lydoxuat');
router.get('/',lydoxuat.index);
router.post('/store',validate.validate_lydoxuat(),lydoxuat.store);
router.get('/edit/:id',lydoxuat.edit);
router.put('/update/:id',validate.validate_lydoxuat(),lydoxuat.update);
router.delete('/delete/:id',lydoxuat.destroy);
router.post('/search',lydoxuat.search);
module.exports = router;