var express = require('express');
var router = express.Router();
const phieunhapkho = require('../app/Controllers/PhieunhapkhoController');
const validate=require('../../request/validate_phieunhapkho');
router.get('/',phieunhapkho.index);
router.post('/store',validate.validate_phieunhapkho(),phieunhapkho.store);
router.get('/edit/:id',phieunhapkho.edit);
router.put('/update/:id',validate.validate_phieunhapkho(),phieunhapkho.update);
router.delete('/delete/:id',phieunhapkho.destroy);
router.post('/search',phieunhapkho.search);
module.exports = router;