var express = require('express');
var router = express.Router();
const phieuxuatkho = require('../app/Controllers/PhieuxuatkhoController');
const validate=require('../../request/validate_phieuxuatkho');
router.get('/',phieuxuatkho.index);
router.post('/store',validate.validate_phieuxuatkho(),phieuxuatkho.store);
router.get('/edit/:id',phieuxuatkho.edit);
router.put('/update/:id',validate.validate_phieuxuatkho(),phieuxuatkho.update);
router.delete('/delete/:id',phieuxuatkho.destroy);
router.post('/search',phieuxuatkho.search);
module.exports = router;