var express = require('express');
var router = express.Router();
const ProductSeries = require('../app/Controllers/ProductSeriesController');
const validate=require('../request//ProductSeriesRequest');
router.get('/listProductSeries',ProductSeries.index);
router.post('/storeProductSeries',validate.checkValidate,ProductSeries.create);
router.get('/editProductSeries',ProductSeries.edit);
router.put('/updateProductSeries/:id',validate.checkValidate,ProductSeries.update);
router.delete('/deleteProductSeries',ProductSeries.destroy);
module.exports = router;
