var express = require('express');
var router = express.Router();
const ProductGroup = require('../app/Controllers/ProductGroupController');
const validate=require('../request//ProductGroupRequest');
router.get('/listProductGroup',ProductGroup.index);
router.post('/storeProductGroup',validate.checkValidate,ProductGroup.create);
router.get('/editProductGroup',ProductGroup.edit);
router.put('/updateProductGroup/:id',validate.checkValidate,ProductGroup.update);
router.delete('/deleteProductGroup',ProductGroup.destroy);
module.exports = router;
