var express = require('express');
var router = express.Router();
const productorder = require('../app/Controllers/ProductOrderController');
const Auth =require('../app/middlewares/authenticatetion');
const Permission =require('../app/middlewares/authorization');
const validate=require('../request/ProductOrderRequest');
router.get('/listProductOrder',productorder.index);
router.post('/createProductOrder',validate.checkValidate,productorder.store);
router.get('/infoProductOrder',productorder.infotoCreate);
router.get('/editProductOrder/:id',productorder.edit);
router.put('/updateProductOrder/:id',productorder.update);
router.get('/showdetail/:id',productorder.showdetail);
router.put('/approveProductOrder/:id',productorder.approve);
router.put('/reapproveProductOrder/:id',productorder.reapprove);
router.put('/cancelProductOrder/:id',productorder.cancel);
router.delete('/delete',productorder.destroy);
module.exports = router;
