var express = require('express');
var router = express.Router();
const productType = require('../app/Controllers/ProductTypeController');
const validate=require('../request/ProductTypeRequest');
router.get('/listProductType',productType.index);
router.post('/storeProductType',validate.checkValidate,productType.create);
router.get('/editProductType',productType.edit);
router.put('/updateProductType/:id',validate.checkValidate,productType.update);
router.delete('/deleteProductType',productType.destroy);
module.exports = router;
