var express = require('express');
var router = express.Router();
const ProductSeries = require('../app/Controllers/ProductSeriesController');
const validate=require('../request//ProductSeriesRequest');
const Auth =require('../app/middlewares/authenticatetion');
const Permision =require('../app/middlewares/authorization');
router.get('/listProductSeries',Auth.checkAuth,Permision.checkPermision,ProductSeries.index);
router.post('/storeProductSeries',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,ProductSeries.create);
router.get('/editProductSeries',Auth.checkAuth,Permision.checkPermision,ProductSeries.edit);
router.put('/updateProductSeries/:id',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,ProductSeries.update);
router.delete('/deleteProductSeries',Auth.checkAuth,Permision.checkPermision,ProductSeries.destroy);
module.exports = router;
