var express = require('express');
var router = express.Router();
const productorder = require('../app/Controllers/ProductOrderController');
const Auth =require('../app/middlewares/authenticatetion');
const Permision =require('../app/middlewares/authorization');
const validate=require('../request/ProductOrderRequest');
router.get('/listProductOrder',Auth.checkAuth,Permision.checkPermision,productorder.index);
router.get('/listSemiProductProductOrder',Auth.checkAuth,productorder.indexSemiProduct);
router.get('/listProductProductOrder',Auth.checkAuth,productorder.indexProduct);
router.post('/createProductOrder',Auth.checkAuth,Permision.checkPermision,productorder.store);
router.get('/infoProductOrder',Auth.checkAuth,Permision.checkPermision,productorder.infotoCreate);
router.get('/editProductOrder/:id',Auth.checkAuth,Permision.checkPermision,productorder.edit);
router.put('/updateProductOrder/:id',Auth.checkAuth,Permision.checkPermision,productorder.update);
router.get('/showdetail/:id',Auth.checkAuth,Permision.checkPermision,productorder.showdetail);
router.put('/approveProductOrder/:id',Auth.checkAuth,Permision.checkPermision,productorder.approve);
router.put('/reapproveProductOrder/:id',Auth.checkAuth,Permision.checkPermision,productorder.reapprove);
router.put('/cancelProductOrder/:id',Auth.checkAuth,Permision.checkPermision,productorder.cancel);
router.delete('/delete',Auth.checkAuth,Permision.checkPermision,productorder.destroy);
module.exports = router;
