var express = require('express');
var router = express.Router();
const ProductGroup = require('../app/Controllers/ProductGroupController');
const validate=require('../request//ProductGroupRequest');
const Auth =require('../app/middlewares/authenticatetion');
const Permision =require('../app/middlewares/authorization');
router.get('/listProductGroup',Auth.checkAuth,Permision.checkPermision,ProductGroup.index);
router.get('/listProductGroup1',Auth.checkAuth,ProductGroup.index1);
router.post('/storeProductGroup',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,ProductGroup.create);
router.get('/editProductGroup',Auth.checkAuth,Permision.checkPermision,ProductGroup.edit);
router.put('/updateProductGroup/:id',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,ProductGroup.update);
router.delete('/deleteProductGroup',Auth.checkAuth,Permision.checkPermision,ProductGroup.destroy);
module.exports = router;
