var express = require('express');
var router = express.Router();
const productType = require('../app/Controllers/ProductTypeController');
const validate=require('../request/ProductTypeRequest');
const Auth =require('../app/middlewares/authenticatetion');
const Permision =require('../app/middlewares/authorization');
router.get('/listProductType',Auth.checkAuth,Permision.checkPermision,productType.index);
router.post('/storeProductType',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,productType.create);
router.get('/editProductType',Auth.checkAuth,Permision.checkPermision,productType.edit);
router.put('/updateProductType/:id',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,productType.update);
router.delete('/deleteProductType',Auth.checkAuth,Permision.checkPermision,productType.destroy);
module.exports = router;
