var express = require('express');
var router = express.Router();
const SemiProduct = require('../app/Controllers/SemiProductController');
const validate=require('../request/SemiProductRequest');
const Auth =require('../app/middlewares/authenticatetion');
const Permision =require('../app/middlewares/authorization');
router.get('/listSemiProduct',Auth.checkAuth,Permision.checkPermision,SemiProduct.index);
router.post('/storeSemiProduct',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,SemiProduct.create);
router.get('/editSemiProduct',Auth.checkAuth,Permision.checkPermision,SemiProduct.edit);
router.put('/updateSemiProduct/:id',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,SemiProduct.update);
router.delete('/deleteSemiProduct',Auth.checkAuth,Permision.checkPermision,SemiProduct.destroy);
module.exports = router;
