var express = require('express');
var router = express.Router();
const SimPackage = require('../app/Controllers/SimPackageComtroller');
const validate=require('../request/SimPackageRequest');
router.get('/listSimPackage',SimPackage.index);
router.post('/storeSimPackage',validate.checkValidate,SimPackage.create);
router.get('/editSimPackage',SimPackage.edit);
router.put('/updateSimPackage/:id',validate.checkValidate,SimPackage.update);
router.delete('/deleteSimPackage',SimPackage.destroy);
module.exports = router;
