var express = require('express');
var router = express.Router();
const SimPackage = require('../app/Controllers/SimPackageComtroller');
const validate=require('../request/SimPackageRequest');
const Auth =require('../app/middlewares/authenticatetion');
const Permision =require('../app/middlewares/authorization');
router.get('/listSimPackage',Auth.checkAuth,Permision.checkPermision,SimPackage.index);
router.post('/storeSimPackage',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,SimPackage.create);
router.get('/editSimPackage',Auth.checkAuth,Permision.checkPermision,SimPackage.edit);
router.put('/updateSimPackage/:id',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,SimPackage.update);
router.delete('/deleteSimPackage',Auth.checkAuth,Permision.checkPermision,SimPackage.destroy);
module.exports = router;
