var express = require('express');
var router = express.Router();
const user = require('../app/Controllers/UserController');
const validate=require('../request/UserRequest');
const upload=require('../helper/upload');
router.get('/listUser',user.listUser);
router.get('/listRoleUser',user.listRoleUser);
router.post('/register',upload.single('avatar'),user.register);
router.post('/login',user.checkLogin);
router.get('/logout',user.checkLogout);
router.get('/infomation',user.Infomation);
router.put('/update',user.updateUser);
router.delete('/delete',user.destroyUser);
router.post('/import',validate.checkValidate,upload.single('image'),user.uploadImage);
module.exports = router;