var express = require('express');
var router = express.Router();
const user = require('../app/Controllers/UserController');
const validate=require('../request/UserRequest');
router.get('/listUser',user.listUser);
router.get('/listRoleUser',user.listRoleUser);
router.post('/register',validate.checkValidate,user.register);
router.post('/login',user.checkLogin);
router.get('/logout',user.checkLogout);
module.exports = router;