var express = require('express');
var router = express.Router();
const user = require('../app/Controllers/UserController');
const validate=require('../request/UserRequest');
const upload=require('../helper/upload');
router.get('/listUser',user.listUser);
router.get('/listRoleUser',user.listRoleUser);
router.post('/registerUser',upload.single('avatar'),user.register);
router.post('/loginUser',user.checkLogin);
router.get('/logoutUser',user.checkLogout);
router.get('/infomationUser',user.Infomation);
router.put('/updateUser',upload.single('avatar'),user.updateUser);
router.delete('/deleteUser',user.destroyUser);
router.put('/changePasswordUser/:id',user.changePassword);
router.post('/testImage',upload.single('image'),user.uploadImage);
router.post('/sendMailUser',user.sendMail);
router.post('/resetPasswordUser/:id',user.resetPassword);
module.exports = router;