var express = require('express');
var router = express.Router();
const vattu = require('../app/Controllers/VattuController');
const validate=require('../../request/validate_vattu');
router.get('/',vattu.index);
router.post('/store',validate.validate_vattu(),vattu.store);
router.get('/edit/:id',vattu.edit);
router.put('/update/:id',validate.validate_vattu(),vattu.update);
router.delete('/delete/:id',vattu.destroy);
router.post('/search',vattu.search);
module.exports = router;