var express = require('express');
var router = express.Router();
const manager_ims = require('../../app/Controllers/IMS/ManagerIMSController');
const validate=require('../../request/IMS/ManagerIMSRequest');
const Auth =require('../../app/middlewares/authenticatetion');
const Permision =require('../../app/middlewares/authorization');
router.get('/listManagerIMS',Auth.checkAuth,Permision.checkPermision,manager_ims.index);
router.post('/storeManagerIMS',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,manager_ims.store);
router.put('/updateManagerIMS/:id',Auth.checkAuth,Permision.checkPermision,validate.checkValidate,manager_ims.update);
router.delete('/deleteManagerIMS/:id',Auth.checkAuth,Permision.checkPermision,manager_ims.destroy);
module.exports = router;
